package at.ac.fhcampuswien.financetracker.ui.theme

import androidx.compose.ui.graphics.Color

/* Light Color Palette is generated by AI */
val L_PrimaryGreen = Color(0xFF4CAF50)              // Soft Green (Primary)
val L_AccentGreen = Color(0xFF81C784)               // Light Green (Secondary)
val L_SubtleGreen = Color(0xFFA5D6A7)               // Pale Green (Tertiary)
val L_BackgroundGreenishWhite = Color(0xFFF1F8E9)   // Light Greenish White (Background)
val L_SurfaceSoftGreen = Color(0xFFE8F5E9)          // Very Light Green (Surface)
val L_TextOnPrimaryWhite = Color(0xFFFFFFFF)        // White (Text on Primary)
val L_TextOnAccentDarkGreen = Color(0xFF1B5E20)     // Dark Green (Text on Secondary)
val L_TextOnTertiaryDeepGreen = Color(0xFF2E7D32)   // Deep Green (Text on Tertiary)
val L_TextOnBackgroundDarkGreen = Color(0xFF1B5E20) // Dark Green (Text on Background)
val L_TextOnSurfaceDeepGreen = Color(0xFF2E7D32)    // Deep Green (Text on Surface)

/* Dark Color Palette is generated by AI */
val D_PrimaryBlue = Color(0xFF90CAF9)               // Light Sky Blue (Primary)
val D_AccentIndigo = Color(0xFF7986CB)              // Soft Indigo (Secondary)
val D_SubtlePurple = Color(0xFFCE93D8)              // Muted Purple (Tertiary)
val D_BackgroundDeepNavy = Color(0xFF121212)        // Almost Black (Background)
val D_SurfaceDarkBlueGray = Color(0xFF1E1E2F)       // Dark Blue-Gray (Surface)
val D_TextOnPrimaryDark = Color(0xFF0D47A1)         // Deep Blue (Text on Primary)
val D_TextOnAccentWhite = Color(0xFFFFFFFF)         // White (Text on Secondary)
val D_TextOnTertiaryWhite = Color(0xFFFFFFFF)       // White (Text on Tertiary)
val D_TextOnBackgroundGray = Color(0xFFB0BEC5)      // Soft Gray (Text on Background)
val D_TextOnSurfaceLavender = Color(0xFFD1C4E9)     // Soft Lavender (Text on Surface)